---
mqtt:
    # Specify your MQTT Broker's hostname or IP address here
    host: mqtt

    # Enable to prevent retaining values
    # retain: false

    # Other optional settings from https://www.npmjs.com/package/mqtt#mqttclientstreambuilder-options
    # username: AzureDiamond
    # password: hunter2

    # Port number to listen on
    port: 8080
